language: python
cache:
    directories:
        $HOME/.cache/pip
python: 2.7
sudo: false
env:
    - TOX_ENV=py27
    - TOX_ENV=py35
    - TOX_ENV=pypy
    - TOX_ENV=flake8
install:
    - pip install tox
script:
    - tox -e $TOX_ENV
