language: python
cache:
    directories:
        $HOME/.cache/pip
python: 3.5
sudo: false
addons:
    apt:
        packages:
            - libzookeeper-mt-dev
env:
    - TOX_ENV=py27
    - TOX_ENV=py35
    - TOX_ENV=pypy
    - TOX_ENV=flake8
install:
    - pip install -U pip
    - pip install tox
script:
    - tox -e $TOX_ENV

deploy:
    provider: pypi
    user: windreamer
    password:
        secure: Qo9ucolE2ajQSbgifbqzfDYD5J09FgYEntXpak1ffPUWxJyeR6H2/uChCGqXC3+ZEkTpzc/MHshHQRRymtPZeHn5etnSHzshWu8njBVLr4I7ft2d5dNGJDxfK2j79HPVnib1MoPNC8kiqP05QD+hyMMQNZDFCHwG1D5bnWNhZYI=
    on:
        tags: true
        repo: douban/pymesos
